common:
  projectName: ${PROJECT_NAME:lala_cloud}
  
  serverName: ${SERVER_NAME:${spring.application.name}}

  dataPath: ${DATA_PATH:/data}

  access: ${env.access}

  open-urls:
    - /favicon.ico
    - /registry/machine
    - /**/open/**
    - /**/druid/**
    - /**/actuator/**
    - /**/error/**

redis:
  host: ${env.redis.host}
  password: ${env.redis.password}
  
mail:
  host: ${env.mail.host}
  port: ${env.mail.port}
  from: ${env.mail.from}
  user: ${env.mail.user}
  pass: ${env.mail.pass}
  subject-prefix: ${env.mail.subjectPrefix}

error:
  catch-print: ${env.error.catchPrint}
  service-print: ${env.error.servicePrint}
  runTime-print: ${env.error.runTimePrint}
  mail-open: ${env.error.mailOpen}
  mail-level: ${env.error.mailLevel}
  mail-receivers: ${env.error.mailReceivers}

log:
  mq: ${env.log.mq}
  mq-topic: ${common.projectName}_log_request_topic
  print: ${env.log.print}

tenant:
  # NONE-非租户模式,COLUMN_NAME-字段模式,TABLE_NAME-表名模式,DATA_SOURCE-数据源模式
  mode: COLUMN_NAME
  column-name: tenant_id
  ignore-tables:
    - ^common_*
    - ^sys_*
    - ^tables*
    - ^columns*

logging:
  config: classpath:logback-common.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

rocketmq:
  name-server: ${env.rocketmq.nameServer}
  producer:
    group: ${common.projectName}_${common.serverName}_producer

sa-token:
  tokenName: Authorization
  timeout: -1
  activity-timeout: ${env.token.activityTimeout}
  is-concurrent: true
  is-share: false
  max-login-count: -1
  token-prefix: Bearer
  is-print: false
  is-log: false
  jwt-secret-key: ${env.token.jwtSecretKey}

  alone-redis:
    host: ${env.token.redisHost}
    port: ${env.token.redisPort}
    password: ${env.token.redisPassword}
    database: ${env.token.redisDatabase}
    timeout: 60s

spring:

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB

  thymeleaf:
    suffix: .html
    prefix: classpath:/templates

  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html
    enabled: true
    request-context-attribute: req
    settings:
      classic_compatible: true
      number_format: 0.##
    suffix: .html
    template-loader-path: classpath:/templates/

  datasource:
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      aop-patterns: "com.jerry.up.lala..*.service.*,com.jerry.up.lala..*.mapper.*"
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        allow:
        url-pattern: /druid/*
        login-username: ${env.druid.username}
        login-password: ${env.druid.password}
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

    dynamic:
      primary: master
      lazy: true
      datasource:
        master:
          lazy: true
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${env.mysql.host}/${mysql.database}?autoReconnect=true&useAffectedRows=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&allowMultiQueries=true
          username: ${env.mysql.username}
          password: ${env.mysql.password}